"""empty message

Revision ID: 6326f6d484f5
Revises: 
Create Date: 2020-03-05 07:46:13.497277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6326f6d484f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
